import os

POSTGRES_PASSWORD = os.environ["POSTGRES_PASSWORD"]
POSTGRES_DB = os.environ["POSTGRES_DB"]
DATABASE_URI = f"postgresql://postgres:{POSTGRES_PASSWORD}@localhost/{POSTGRES_DB}"
USE_API_STUBS = True
SQLALCHEMY_ECHO = True
DEBUG = True
ALLOWED_EXTENSIONS = ["csv"]
SECRET_KEY = "TRU3S3CR3T"
HTTP_AUTHORIZATION = "token"
