"""add user token

Revision ID: 0b45bbed7a9d
Revises: 24f48a37cf77
Create Date: 2019-09-12 19:08:32.185653

"""
from alembic import op
import sqlalchemy as sa
from backend.models import HashedToken


# revision identifiers, used by Alembic.
revision = "0b45bbed7a9d"
down_revision = "24f48a37cf77"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("auth_token", HashedToken(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "auth_token")
    # ### end Alembic commands ###
