"""delete column is_collected

Revision ID: 1ad88fb78c91
Revises: aa89eaeeeec7
Create Date: 2019-07-05 19:10:12.757620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad88fb78c91'
down_revision = 'aa89eaeeeec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensordata', 'is_collected')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensordata', sa.Column('is_collected', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
