"""add user_id to sensordata

Revision ID: 215eea730e64
Revises: 0b45bbed7a9d
Create Date: 2019-09-29 18:18:59.459492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215eea730e64'
down_revision = '0b45bbed7a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensordata', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensordata', 'user_id')
    # ### end Alembic commands ###
