"""add user model

Revision ID: 24f48a37cf77
Revises: 321c59b1b4fb
Create Date: 2019-09-10 19:54:07.764247

"""
from alembic import op
import sqlalchemy as sa
from backend.models import EncryptedPassword

# revision identifiers, used by Alembic.
revision = '24f48a37cf77'
down_revision = '321c59b1b4fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('password', EncryptedPassword(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
