"""add unit string rename channel to field name

Revision ID: 321c59b1b4fb
Revises: 6f92e6466bf1
Create Date: 2019-08-01 17:54:50.460347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321c59b1b4fb'
down_revision = '6f92e6466bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensordata', sa.Column('field_name', sa.String(), nullable=True))
    op.add_column('sensordata', sa.Column('unit_string', sa.String(), nullable=True))
    op.drop_column('sensordata', 'channel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensordata', sa.Column('channel', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('sensordata', 'unit_string')
    op.drop_column('sensordata', 'field_name')
    # ### end Alembic commands ###
