"""add updated_at

Revision ID: 6f92e6466bf1
Revises: 7cdcfaaf2ce7
Create Date: 2019-07-06 12:26:12.610746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f92e6466bf1'
down_revision = '7cdcfaaf2ce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debugcode', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('sensor', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor', 'updated_at')
    op.drop_column('debugcode', 'updated_at')
    # ### end Alembic commands ###
