"""Rebuild all tables

Revision ID: 7cdcfaaf2ce7
Revises: 
Create Date: 2019-07-05 20:23:05.157260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cdcfaaf2ce7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debug',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debugcode',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('mac_addr', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'device_id')
    )
    op.create_table('sensordata',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('app_key', sa.String(), nullable=True),
    sa.Column('net_key', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('value', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensordata')
    op.drop_table('sensor')
    op.drop_table('debugcode')
    op.drop_table('debug')
    # ### end Alembic commands ###
