"""add created_at field

Revision ID: 7e0a65bb110c
Revises: c7698f6db48a
Create Date: 2019-05-17 09:58:06.409721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0a65bb110c'
down_revision = 'c7698f6db48a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensordata', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensordata', 'created_at')
    # ### end Alembic commands ###
