"""change format of sensordata table

Revision ID: aa89eaeeeec7
Revises: 56cf4eebeeac
Create Date: 2019-07-05 18:55:29.873975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa89eaeeeec7'
down_revision = '56cf4eebeeac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensordata',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('app_key', sa.String(), nullable=True),
    sa.Column('net_key', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('value', sa.BigInteger(), nullable=True),
    sa.Column('is_collected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    op.create_table('sensordata',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('app_key', sa.String(), nullable=True),
                    sa.Column('net_key', sa.String(), nullable=True),
                    sa.Column('device_id', sa.String(), nullable=True),
                    sa.Column('channels', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

