"""first reversion

Revision ID: ad970d351fc3
Revises: 
Create Date: 2019-04-19 13:43:06.274483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad970d351fc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensordata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_key', sa.String(), nullable=True),
    sa.Column('net_key', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensordata')
    # ### end Alembic commands ###
